from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_dashboard_summary_pdf(file_path, title, data):
    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=35,
        leftMargin=35,
        topMargin=35,
        bottomMargin=35
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1E3A8A"),
        spaceAfter=18
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#475569"),
        spaceAfter=20
    )

    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        fontSize=15,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=15,
        spaceAfter=10
    )

    normal_style = ParagraphStyle(
        "NormalStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#334155"),
        leading=14
    )

    story = []

    story.append(Paragraph(title, title_style))
    story.append(
        Paragraph(
            "Advanced AI Demand Forecasting Phase 4 - Dashboard Summary Report",
            subtitle_style
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    kpi_data = [
        ["Metric", "Value"],
        ["Total Datasets", data.get("Total Datasets", 0)],
        ["Total Forecasts", data.get("Total Forecasts", 0)],
        ["Total AI Insights", data.get("Total AI Insights", 0)],
        ["Latest Predicted Demand", data.get("Latest Predicted Demand", 0)],
        ["Latest Confidence Score", f"{data.get('Latest Confidence Score', 0)}%"],
        ["Latest Trend", data.get("Latest Trend", "No forecast available")]
    ]

    table = Table(
        kpi_data,
        colWidths=[230, 230]
    )

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F8FAFC")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
                    colors.HexColor("#F8FAFC"),
                    colors.HexColor("#EEF2FF")
                ]),
                ("PADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )

    story.append(Paragraph("Dashboard KPI Summary", section_style))
    story.append(table)

    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph("Business Interpretation", section_style))
    story.append(
        Paragraph(
            "This report summarizes the current forecasting platform activity, "
            "including uploaded datasets, generated forecasts, AI insights, "
            "latest predicted demand, confidence score and trend direction.",
            normal_style
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Recommendation", section_style))
    story.append(
        Paragraph(
            "Use the predicted demand and confidence score to improve stock planning, "
            "procurement decisions, inventory optimization, and business forecasting strategy.",
            normal_style
        )
    )

    story.append(Spacer(1, 0.4 * inch))

    footer_table = Table(
        [["Generated By", "Advanced AI Demand Forecasting Phase 4"]],
        colWidths=[150, 310]
    )

    footer_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#E0F2FE")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#075985")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 10),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#7DD3FC")),
            ]
        )
    )

    story.append(footer_table)

    doc.build(story)